### ISSUE TITLE
Website search is broken

### ISSUE THREAD

**Issue by andreyc0d3r** [reduxjs/react-redux#2151]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

search doesnt work https://react-redux.js.org/

### What is the expected behavior?

expected working search

### Which browser and OS are affected by this issue?

chrome

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by timdorr** [comment]
I don't think I have access to the right Algolia projects, but we just need to set the app ID that was removed in this commit: 1bd4b25d507dd53e99d5b69b8058525052d3eef2

cc: @markerikson

**Comment by markerikson** [comment]
Yeah, the Algolia setup has been broken or weird for the last year or so.

We've got 2-3 different projects in Algolia. There was an old-style key for an old project and some kind of upgrade/migration step that didn't get done by their deadline. I thought I fixed it with a new key after talking to support, but maybe that didn't work right?

**Comment by kurenov** [comment]
Hey guys,

Looks like the **appId** is still required for the current setup. With the current config `appId: ' '`, requests fail because the **appId** is used in the URL generation `https://{APPLICATION_ID}.algolia.net`.

When I reverted the value for **appId** based on https://github.com/reduxjs/react-redux/commit/1bd4b25d507dd53e99d5b69b8058525052d3eef2, I no longer got the DNS error above. However, there is new 400 error:

```
{
  "message": "indexName is not valid",
  "status": 400
}
```

Based on this [support article](https://support.algolia.com/hc/en-us/articles/15516676624145--DocSearch-Why-do-I-get-the-error-Invalid-indexName), this error occurs in two cases:

1. indexName does not match the indexName issued in your DocSearch acceptance email
2. incorrect API key is used

Then I tried to fetch all indecies via GET https://g15kg9hemq.algolia.net/1/indexes?x-algolia-api-key=2d058d216b7fd5d68d481fd48ee72c06&x-algolia-application-id=G15KG9HEMQ which resulted in 403 error below:

```
{"message":"Invalid Application-ID or API key","status":403}
```

Looks like the App ID & API key are no longer valid.

**Comment by inblossoms** [comment]
Hi dude, excuse me. The current document search is still not working 🫣.

**Comment by markerikson** [comment]
I just got done switching all the Redux docs sites over to Canary ( https://github.com/fastrepl/canary ) + Pagefind, which build a local search index on each docs deploy.  This appears to work well (and actually displays nicer results than Algolia did!).  Hopefully that resolves this issue for good.
